### PR TITLE
remove lorem ipsum from header

### PR DESCRIPTION
**Pull request by ivanzusko**

### CODE REVIEW

**Comment by c4pone** [comment]
why do you comment it out instead of removing it ?

**Comment by ivanzusko** [comment]
@c4pone because very soon it will be returned with necessary functionality

**Comment by c4pone** [comment]
then what is the purpose of this pr if you anyway going to replace it soon ?

**Comment by c4pone** [comment]
+1

**Comment by Vxplus** [comment]
👍

**Pull request merged**
